-- 1.
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;
ALTER SESSION SET NLS_DATE_FORMAT = 'RR/MM/DD';
-- 2.
SELECT PROFESSOR_NAME,PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;
-- 3.
SELECT PROFESSOR_NAME 교수이름
FROM TB_PROFESSOR;
-- 4.
SELECT SUBSTR(PROFESSOR_NAME,2)
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 2;
-- 5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE 19 = MONTHS_BETWEEN(ENTRANCE_DATE,SUBSTR(STUDENT_SSN,0,6)/12);
-- 6.