CREATE TABLE MATCH_POST(
    MATCH_NO NUMBER,
    MATCH_ID VARCHAR2(50) UNIQUE,
    MATCH_POST_NAME VARCHAR2(100) NOT NULL,
    MATCH_POST_WRITE VARCHAR2(1000) NOT NULL,
    MATCH_POST_LIKE CHAR(1) CHECK(MATCH_POST_LIKE IN ('Y','N')),
    MATCH_WRITE_DATE DATE DEFAULT SYSDATE,
    MATCH_POST_URL VARCHAR2(500),
    MATCH_CONSENT CHAR(1) CHECK(MATCH_CONSENT IN ('Y','N')),
    NOTICE CHAR(1) CHECK(NOTICE IN ('Y','N')),
    CONSTRAINT MATCH_POST_MATCH_NO_PK PRIMARY KEY(MATCH_NO)
);
    
DROP TABLE MATCH_POST;
SELECT * FROM MATCH_POST;
    